name:                 z-pact-tng-z-unsafe
version:              5.4.1
package-name:         pact-tng
lib-name:             unsafe
visibility:           public
id:                   pact-tng-5.4.1-inplace-unsafe
key:                  pact-tng-5.4.1-inplace-unsafe
license:              BSD-3-Clause
copyright:            Copyright (C) 2022 Kadena
maintainer:           jose@kadena.io
author:               Jose Cardona
homepage:             https://github.com/kadena-community/pact-5
synopsis:             Smart contract language library and REPL
description:
    Pact is a transactional, database-focused, Turing-incomplete, interpreted language for smart contracts,
    logic to be deployed and executed on a blockchain/distributed ledger. For more information see
    <http://kadena.io/pact>.

category:             Language
abi:                  inplace
exposed-modules:      Data.Foldable.Unsafe Data.List.Unsafe
import-dirs:
    /mnt/chainweb/projectsCW/pact5-pq/dist-newstyle/build/x86_64-linux/ghc-9.6.7/pact-tng-5.4.1/l/unsafe/build/unsafe

library-dirs:
    /mnt/chainweb/projectsCW/pact5-pq/dist-newstyle/build/x86_64-linux/ghc-9.6.7/pact-tng-5.4.1/l/unsafe/build/unsafe
    /usr/lib/x86_64-linux-gnu

library-dirs-static:
    /mnt/chainweb/projectsCW/pact5-pq/dist-newstyle/build/x86_64-linux/ghc-9.6.7/pact-tng-5.4.1/l/unsafe/build/unsafe
    /usr/lib/x86_64-linux-gnu

dynamic-library-dirs:
    /mnt/chainweb/projectsCW/pact5-pq/dist-newstyle/build/x86_64-linux/ghc-9.6.7/pact-tng-5.4.1/l/unsafe/build/unsafe
    /usr/lib/x86_64-linux-gnu

data-dir:             /mnt/chainweb/projectsCW/pact5-pq/.
hs-libraries:         HSpact-tng-5.4.1-inplace-unsafe
include-dirs:         /home/notbob/.local/include
depends:              base-4.18.3.0
haddock-interfaces:
    /mnt/chainweb/projectsCW/pact5-pq/dist-newstyle/build/x86_64-linux/ghc-9.6.7/pact-tng-5.4.1/l/unsafe/doc/html/pact-tng/unsafe.haddock

haddock-html:
    /mnt/chainweb/projectsCW/pact5-pq/dist-newstyle/build/x86_64-linux/ghc-9.6.7/pact-tng-5.4.1/l/unsafe/doc/html/pact-tng
