name:                 z-pact-tng-z-pact-crypto
version:              5.4.1
package-name:         pact-tng
lib-name:             pact-crypto
id:                   pact-tng-5.4.1-inplace-pact-crypto
key:                  pact-tng-5.4.1-inplace-pact-crypto
license:              BSD-3-Clause
copyright:            Copyright (C) 2022 Kadena
maintainer:           jose@kadena.io
author:               Jose Cardona
homepage:             https://github.com/kadena-community/pact-5
synopsis:             Smart contract language library and REPL
description:
    Pact is a transactional, database-focused, Turing-incomplete, interpreted language for smart contracts,
    logic to be deployed and executed on a blockchain/distributed ledger. For more information see
    <http://kadena.io/pact>.

category:             Language
abi:                  inplace
exposed-modules:
    Pact.Core.Crypto.Base64 Pact.Core.Crypto.Hash.Keccak256
    Pact.Core.Crypto.Hash.Poseidon Pact.Core.Crypto.Pairing
    Pact.Core.Crypto.Pairing.Fields

import-dirs:
    /mnt/chainweb/projectsCW/pact5-pq/dist-newstyle/build/x86_64-linux/ghc-9.6.7/pact-tng-5.4.1/l/pact-crypto/build/pact-crypto

library-dirs:
    /mnt/chainweb/projectsCW/pact5-pq/dist-newstyle/build/x86_64-linux/ghc-9.6.7/pact-tng-5.4.1/l/pact-crypto/build/pact-crypto
    /usr/lib/x86_64-linux-gnu

library-dirs-static:
    /mnt/chainweb/projectsCW/pact5-pq/dist-newstyle/build/x86_64-linux/ghc-9.6.7/pact-tng-5.4.1/l/pact-crypto/build/pact-crypto
    /usr/lib/x86_64-linux-gnu

dynamic-library-dirs:
    /mnt/chainweb/projectsCW/pact5-pq/dist-newstyle/build/x86_64-linux/ghc-9.6.7/pact-tng-5.4.1/l/pact-crypto/build/pact-crypto
    /usr/lib/x86_64-linux-gnu

data-dir:             /mnt/chainweb/projectsCW/pact5-pq/.
hs-libraries:         HSpact-tng-5.4.1-inplace-pact-crypto
include-dirs:         /home/notbob/.local/include
depends:
    base-4.18.3.0
    base64-bytestring-1.2.1.0-93884c33d5319460885c22448a85b73b51ecd5fa4dd2eb84f32aab7cacf68661
    bytestring-0.11.5.4 deepseq-1.4.8.1
    groups-0.5.3-cfd3c65000aa93a1227de8fb2276b4cde705b2ee114d42d85b20e5287b835e5f
    hashes-0.3.0.1-ecd6a1a3168f72de4b6cf92cc3ea0785532e0fb42d368fc21695d4e1f1c2f5a8
    mod-0.2.1.0-7bc391a4acd4e8bdbe92562ce205322a13e39a0bb4bfb0aa9af8209a0d3e8616
    poly-0.5.1.0-a9bdaa2223fbac0c832ded1c0a86048df9ff46a044da9a75c02a24ed6e527c53
    primitive-0.9.1.0-3528347ad25d55425546d2a0da9fc144f46f4d8b2cf04dd14c3e061d311202c3
    safe-exceptions-0.1.7.4-6f66ec05323df260b29966a8dfb6768c089c3f38c603a2783cf2d29fa790b34f
    semirings-0.7-bf98817f06c52e100be89d92f1b3c52fdedd7d87429f34480e65e474300f37f8
    text-2.0.2
    vector-0.13.2.0-1f613ccec062f0764e679a2164bb9fba389c833ebe781e0aee730877926fe96b

haddock-interfaces:
    /mnt/chainweb/projectsCW/pact5-pq/dist-newstyle/build/x86_64-linux/ghc-9.6.7/pact-tng-5.4.1/l/pact-crypto/doc/html/pact-tng/pact-crypto.haddock

haddock-html:
    /mnt/chainweb/projectsCW/pact5-pq/dist-newstyle/build/x86_64-linux/ghc-9.6.7/pact-tng-5.4.1/l/pact-crypto/doc/html/pact-tng
